// Downloads the app fonts from Google Fonts into public/fonts/ and writes public/fonts.css,
// so the PWA works offline and makes no third-party requests.
//   Manrope   (variable, wght 400–800): latin + cyrillic, plus a tiny "₽" subset
//   Unbounded (variable, wght 500–600): latin + cyrillic
// The ruble sign U+20BD lives in Google's latin-ext subset (15 KB); instead of shipping that
// file we request a one-glyph Manrope kit with &text=₽ (~1 KB), which keeps every amount in Manrope.
// Usage: node tools/fetch-fonts.mjs        (Node ≥ 20; behind a proxy: NODE_USE_ENV_PROXY=1)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "public", "fonts");
const cssFile = path.join(root, "public", "fonts.css");
// a modern Chrome UA makes Google Fonts answer with woff2 + unicode-range subsets
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36";

const REQUESTS = [
  { family: "Manrope", query: "family=Manrope:wght@400..800", subsets: ["cyrillic", "latin"] },
  { family: "Unbounded", query: "family=Unbounded:wght@500..600", subsets: ["cyrillic", "latin"] },
  { family: "Manrope", query: "family=Manrope:wght@400..800&text=" + encodeURIComponent("₽"), subsets: ["ruble"], textKit: true },
];

async function get(url, as) {
  const res = await fetch(url, { headers: { "user-agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return as === "text" ? res.text() : Buffer.from(await res.arrayBuffer());
}

// "/* cyrillic */\n@font-face { … }" → [{ subset, family, style, weight, src, range }]
function parseFaces(css) {
  const faces = [];
  const re = /(?:\/\*\s*([\w-]+)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g;
  for (let m; (m = re.exec(css));) {
    const body = m[2];
    const prop = name => (body.match(new RegExp(`${name}\\s*:\\s*([^;]+);`)) || [])[1]?.trim();
    const url = (prop("src") || "").match(/url\(([^)]+)\)\s*format\(['"]?woff2['"]?\)/);
    if (!url) throw new Error("no woff2 src in @font-face:\n" + body);
    faces.push({
      subset: m[1] || null,
      family: (prop("font-family") || "").replace(/['"]/g, ""),
      style: prop("font-style") || "normal",
      weight: prop("font-weight") || "400",
      src: url[1].replace(/['"]/g, ""),
      range: prop("unicode-range") || null,
    });
  }
  return faces;
}

const MAGIC_WOFF2 = Buffer.from("wOF2");

fs.mkdirSync(outDir, { recursive: true });
const blocks = [];
const files = [];
for (const r of REQUESTS) {
  const css = await get(`https://fonts.googleapis.com/css2?${r.query}&display=swap`, "text");
  const faces = parseFaces(css);
  for (const subset of r.subsets) {
    const face = r.textKit ? faces[0] : faces.find(f => f.subset === subset);
    if (!face) throw new Error(`${r.family}: subset "${subset}" not found in Google Fonts CSS`);
    if (face.family !== r.family) throw new Error(`unexpected family ${face.family}`);
    const data = await get(face.src);
    if (!data.subarray(0, 4).equals(MAGIC_WOFF2)) throw new Error(`${face.src} is not a woff2 file`);
    const name = `${r.family.toLowerCase()}-${subset}.woff2`;
    fs.writeFileSync(path.join(outDir, name), data);
    files.push(`${name} ${(data.length / 1024).toFixed(1)} KB`);
    // the one-glyph kit has no meaningful unicode-range of its own: pin it to the ruble sign
    const range = r.textKit ? "U+20BD" : face.range;
    blocks.push(`/* ${r.family} ${subset} */
@font-face {
  font-family: "${r.family}";
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url("fonts/${name}") format("woff2");${range ? `\n  unicode-range: ${range};` : ""}
}`);
  }
}

const header = `/* Self-hosted Google Fonts (SIL Open Font License 1.1, see LICENSES.md).
   Generated by tools/fetch-fonts.mjs — do not edit by hand. */\n`;
fs.writeFileSync(cssFile, header + blocks.join("\n") + "\n");
console.log(files.map(f => "  public/fonts/" + f).join("\n"));
console.log(`fonts: wrote public/fonts.css (${blocks.length} faces)`);
