// Regenerates src/icons.js: the lucide icons the app actually uses (scans src/ for icon("Name"),
// data-icon="Name" and icon: "Name"). Dev-time only; the output is committed.
// Usage: node tools/icons-subset.mjs [path/to/lucide.min.js]
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const LUCIDE_VERSION = "0.460.0";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "src");

let lucidePath = process.argv[2];
if (!lucidePath) {
  lucidePath = path.join(root, "node_modules", ".cache", `lucide-${LUCIDE_VERSION}.min.js`);
  if (!fs.existsSync(lucidePath)) {
    const res = await fetch(`https://cdn.jsdelivr.net/npm/lucide@${LUCIDE_VERSION}/dist/umd/lucide.min.js`);
    if (!res.ok) throw new Error(`lucide download failed: ${res.status}`);
    fs.mkdirSync(path.dirname(lucidePath), { recursive: true });
    fs.writeFileSync(lucidePath, await res.text());
  }
}
const lucide = createRequire(import.meta.url)(path.resolve(lucidePath));

const names = new Set();
for (const f of fs.readdirSync(src)) {
  if (!/\.(js|html)$/.test(f) || f === "icons.js") continue;
  const text = fs.readFileSync(path.join(src, f), "utf8");
  for (const re of [/\bicon\(\s*"([A-Z][A-Za-z0-9]*)"/g, /data-icon="([A-Z][A-Za-z0-9]*)"/g, /\bicon:\s*"([A-Z][A-Za-z0-9]*)"/g])
    for (const m of text.matchAll(re)) names.add(m[1]);
}
// names chosen at run time (e.g. a ternary inside icon(...)) are listed here
for (const n of (process.env.EXTRA_ICONS || "TrendingUp,TrendingDown").split(",").filter(Boolean)) names.add(n);

const out = {};
const missing = [];
for (const n of [...names].sort()) {
  const node = lucide.icons[n];
  if (!node) { missing.push(n); continue; }
  out[n] = node[2];
}
if (missing.length) { console.error("Unknown lucide icons:", missing.join(", ")); process.exit(1); }
const body = `/* Generated by tools/icons-subset.mjs from lucide ${LUCIDE_VERSION} (ISC License, https://lucide.dev). Do not edit. */
(() => { window.BUDGET_ICONS = ${JSON.stringify(out)}; })();
`;
fs.writeFileSync(path.join(src, "icons.js"), body);
console.log(`src/icons.js: ${Object.keys(out).length} icons, ${body.length} bytes`);
